### ISSUE TITLE
Extend the Bindings parameter to work with structs

### ISSUE THREAD

**Issue by thessem** [osteele/liquid#23]
Currently
```
	params := map[string]interface{}{
		"message": Message{
			Text: "hello",
		},
	}
	engine := liquid.NewEngine()
	template := "{{ message.Text }}"
	str, err := engine.ParseAndRenderString(template, params)
	log.Printf("Err: %v\n%v", err, str)
```
doesn't work as expected, but 
```
	params := map[string]interface{}{
		"message": map[string]interface{}{
			"Text": "hello",
		},
	}
	engine := liquid.NewEngine()
	template := "{{ message.Text }}"
	str, err := engine.ParseAndRenderString(template, params)
	log.Printf("Err: %v\n%v", err, str)
```
does. The text/template and html/template libraries in the go standard library allow you to traverse through any objects (maps, structs, slices and pointers to these) and use them in the templating engine, as in my first example.

A decent workaround for this is the `github.com/fatih/structs` `Map()` function, which converts your struct structure into a map based structure, but this has two problems in my use case. 1. My data struct is very large and this is a lot of processing, and 2. it preserves elements of my data struct that are *map[string]interface{} (which need to be like this to work with the rest of my program), which as far as I can tell
```
	params := map[string]interface{}{
		"message": &map[string]interface{}{
			"Text": "hello",
		},
	}
	engine := liquid.NewEngine()
	template := "{{ message.Text }}"
	str, err := engine.ParseAndRenderString(template, params)
	log.Printf("Err: %v\n%v", err, str)
```
also doesn't work correctly.

Are you planning on extending to copy this behaviour (from text/template or even https://github.com/acstech/liquid) in your current library, or do you consider it out of scope?

**Comment by osteele** [comment]
Compatibility with text/template seems like a good idea. I'll add this.

**Comment by osteele** [comment]
Your examples, with `&map[string]interface{}` and `Message{Text: "hello"}`, now work in master.

**Comment by thessem** [comment]
This fixes my issue, thanks!
