### ISSUE TITLE
Cannot compile on armv7

### ISSUE THREAD

**Issue by abeMedia** [osteele/liquid#52]
## Checklist

- [x] I have searched the [issue list](https://github.com/osteele/liquid/issues)
- [ ] I have tested my example against Shopify Liquid. (This isn't necessary if the actual behavior is a panic, or an error for which `IsTemplateError` returns false.)

## Expected Behavior
I can compile for armv7

## Actual Behavior
Throws error: `yaccpar:452: constant 4294967295 overflows int`

## Detailed Description
It appears somewhere there's a constant which is too large for anything but a 64bit environment. 

## Possible Solution
Would be good to add some build tags to have a different value for other environments.

**Comment by osteele** [comment]
I've just merged @bendoerr's PR#47, which I believe fixes this. I don't currently have a way to verify this (see PR #49), so I'm leaving this bug open until this is confirmed.

**Comment by bendoerr** [comment]
WOW Thanks @osteele! I intended to get to it last week but lots got in the way. I'll have someone give it a test soon.

**Comment by abeMedia** [comment]
Will give it a try after work tonight. Thanks!

**Comment by abeMedia** [comment]
Just tested it and can confirm it's working on armv7 now. Thanks a lot @osteele and @bendoerr!
